# Generated by Django 4.2.21 on 2025-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
