# Generated by Django 4.2.21 on 2025-05-31 06:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
