# Generated by Django 4.2.21 on 2025-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Select a rating from 1 to 5 stars'),
        ),
    ]
