# Generated by Django 4.2.21 on 2025-06-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_reviewpost_featured_image_reviewpost_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
